version: '3.2'

services:
  db:
    image: postgres
    environment:
      - DEBUG=false

  web:
    image: skills/web:latest
    build: ../api
    environment:
      - API_HOST=api
    depends_on:
      - api

  api:
    build: .
    restart: always
    command: yarn test --watch
    environment:
      - DB_USER=definitelynotroot
      - DB_PASS=Sm@11ButMyTea
      - DB_NAME=skills
      - DB_HOST=db
      - DB_PORT=5432
      - APP_HOST=0.0.0.0
    volumes:
      - ".:/usr/src/app/"
    ports:
      - "3000:3000"
    depends_on:
      - db

