#!/bin/sh

set -e -u

targetFlag=""
if [ ! -z ${target+x} ]; then
  targetFlag="-t ${target}"
fi
echo "Target flag: ${targetFlag}"

echo /usr/src/node_modules/.bin/artillery run "repo/artillery.yml" \
  -e "${env}" \
  -o "report.json" \
  ${targetFlag}

/usr/src/node_modules/.bin/artillery run "repo/artillery.yml" \
  -e "${env}" \
  -o "report.json" \
  ${targetFlag}
