---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

inputs:
- name: repo

outputs:
- name: release-name

run:
  dir: repo
  path: sh
  args: [ci/script/create-release-name]
