---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

inputs:
- name: repo

outputs:
- name: release_name
  path: release_name

run:
  dir: repo
  path: sh
  args: [ci/tasks/create-release-name]
