kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: client
rules:
- verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  apiGroups:
  - ""
  - "extensions"
  - "apps"
  resources:
  - "deployments"
  - "replicasets"
  - "pods"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: concourse-tiller
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: client
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: client
