#!/bin/bash
# vim: ft=sh

set -u -x

changelog_file_name="CHANGELOG.md"
rm -f "${changelog_file_name}"
conventional-changelog -p "angular" -i "${changelog_file_name}" -s -r 0
git status --short | grep -q CHANGELOG.md
res=$?
echo "Res: ${res}"
if [ ${res} = 0 ]; then
  echo "changes: "
  git diff -- CHANGELOG.md | cat
fi
# git add CHANGELOG.md
# git commit -m "docs: Update README.md"
# git push
