jobs:
- name: test-merge-requests
  public: true
  serial: true
  plan:
  - get: repo
    resource: merge-requests
    trigger: true
  - put: merge-requests
    params:
      repository: repo
      status: running
  - task: run-tests
    file: repo/ci/tasks/run-tests.yml
  on_failure:
    put: merge-requests
    params:
      repository: repo
      status: failed
  on_success:
    put: merge-requests
    params:
      repository: repo
      status: success

resources:
- name: merge-requests
  type: merge-request
  source:
    uri: {{gitlab-repo}}
    private_key: {{gitlab-private-key}}
    private_token: {{gitlab-private-token}}

resource_types:
- name: merge-request
  type: docker-image
  source:
    repository: jakedsouza/gitlab-merge-request-resource
