jobs:
- name: build
  public: true
  serial: true
  plan:
  - get: version
  - get: repo
    trigger: true
  - put: skills-api-image
    params:
      build: repo
      tag: version/number
      tag_as_latest: true
      cache_tag: latest
      cache: true
  - put: version
    params: {bump: minor}

resources:
- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: {{gitlab-repo}}
    branch: version
    file: version
    private_key: {{gitlab-private-key}}

- name: repo
  type: git
  source:
    uri: {{gitlab-repo}}
    branch: master
    private_key: {{gitlab-private-key}}

- name: skills-api-image
  type: docker-image
  source:
    repository: senforsce/skills-api
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: jcderr/concourse-kubernetes-resource
