jobs:
- name: build
  public: true
  serial: true
  plan:
  - get: version
  - get: repo
    trigger: true
  - put: skills-api-image
    params:
      build: repo
      tag: version/number
      tag_as_latest: true
      cache_tag: latest
      cache: true
  - put: version
    params: {bump: minor}
- name: deploy
  public: true
  serial: true
  plan:
  - aggregate:
    - get: version
      passed: [build]
      trigger: true
    - get: repo
      passed: [build]
      trigger: true
    - get: skills-api-image
      passed: [build]
      trigger: true
    - put: test-env
    params:
      chart: repo/kubernetes/skills-api
      values: repo/kubernetes/skills-api/values.yaml
      wait_until_ready: true
      release: repo/kubernetes/skills-api/release_name
      override_values:
      - key: replicaCount
        value: 1
      - key: version
        path: version/number
      - key: image.tag
        path: version/number
      - key: ingress.hosts[0]
        value: test.((version/number))
      - key: ingress.enabled
        value: false

resources:
- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: {{gitlab-repo}}
    branch: version
    file: version
    private_key: {{gitlab-private-key}}

- name: repo
  type: git
  source:
    uri: {{gitlab-repo}}
    branch: master
    private_key: {{gitlab-private-key}}

- name: skills-api-image
  type: docker-image
  source:
    repository: senforsce/skills-api
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: test-env
  type: helm
  source:
    cluster_url: https://kube-master.domain.example
    cluster_ca: _base64 encoded CA pem_
    admin_key: _base64 encoded key pem_
    admin_cert: _base64 encoded certificate pem_
    namespace: test

resource_types:

- name: kubernetes
  type: docker-image
  source:
    repository: jcderr/concourse-kubernetes-resource

- name: helm
  type: docker-image
  source:
    repository: linkyard/concourse-helm-resource
